# Generated by Django 5.0.3 on 2024-03-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='books',
            name='back_thumbnail',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='books.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='front_thumbnail',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='books',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
