# Generated by Django 5.0.3 on 2024-03-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
